Repository foreco-ibaji/Wiz-Server, pull requests merged in 2023-09, with the labels that each got.

#80 setting: 스웨거 config 추가 설정
  src/main/java/com/sesacthon/global/swagger/SwaggerConfig.java
Labels: 📋 Docs, 🛠 Fix

#83 Fix/#82
  src/main/java/com/sesacthon/foreco/category/dto/response/CategorySimpleDto.java
  src/main/java/com/sesacthon/foreco/category/entity/RegionCategory.java
  src/main/java/com/sesacthon/foreco/category/entity/Trash.java
  src/main/java/com/sesacthon/foreco/member/entity/Member.java
  src/main/java/com/sesacthon/foreco/region/entity/Region.java
  src/main/java/com/sesacthon/foreco/trash/entity/TrashInfo.java
Labels: 🛠 Fix

#86 feat:관련쓰레기조회 api 구현
  src/main/java/com/sesacthon/foreco/category/entity/Trash.java
  src/main/java/com/sesacthon/foreco/category/repository/TrashRepository.java
  src/main/java/com/sesacthon/foreco/trash/controller/TrashController.java
  src/main/java/com/sesacthon/foreco/trash/dto/RelevantTrashDto.java
  src/main/java/com/sesacthon/foreco/trash/dto/RelevantTrashesDto.java
  src/main/java/com/sesacthon/foreco/trash/entity/TrashInfo.java
  src/main/java/com/sesacthon/foreco/trash/repository/TrashInfoRepository.java
  src/main/java/com/sesacthon/foreco/trash/service/TrashService.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature, ⭐ Refactoring

#91 feat: 검색결과 조회 기능 구현
  build.gradle
  src/main/java/com/sesacthon/foreco/category/repository/RegionCategoryRepository.java
  src/main/java/com/sesacthon/foreco/category/repository/TrashQueryRepository.java
  src/main/java/com/sesacthon/foreco/mock/MockController.java
  src/main/java/com/sesacthon/foreco/trash/controller/TrashController.java
  src/main/java/com/sesacthon/foreco/trash/dto/SearchedTrashDto.java
  src/main/java/com/sesacthon/foreco/trash/dto/SearchedTrashesDto.java
  src/main/java/com/sesacthon/foreco/trash/service/TrashService.java
  src/main/java/com/sesacthon/global/config/QuerydslConfig.java
Labels: ✨ Feature, ⚙ Setting

#94 feat: JPQL로 검색 기능 & AI 모델 결과 조회 기능 구현
  src/main/java/com/sesacthon/foreco/category/repository/RegionCategoryRepository.java
  src/main/java/com/sesacthon/foreco/category/repository/TrashRepository.java
  src/main/java/com/sesacthon/foreco/mock/MockController.java
  src/main/java/com/sesacthon/foreco/trash/controller/TrashController.java
  src/main/java/com/sesacthon/foreco/trash/dto/SearchedTrashDto.java
  src/main/java/com/sesacthon/foreco/trash/dto/SearchedTrashesDto.java
  src/main/java/com/sesacthon/foreco/trash/service/TrashService.java
  src/main/java/com/sesacthon/infra/s3/controller/S3Controller.java
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#103 refactor: /api/v1/image api응답 데이터에 id필드 추가
  src/main/java/com/sesacthon/foreco/category/repository/TrashRepository.java
  src/main/java/com/sesacthon/infra/s3/dto/UploadDto.java
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
Labels: ⭐ Refactoring, 🛠 Fix

#104 feat: S3 아이콘 이미지 불러오는 기능 추가 구현
  src/main/java/com/sesacthon/foreco/category/entity/Icon.java
  src/main/java/com/sesacthon/foreco/category/entity/Trash.java
  src/main/java/com/sesacthon/foreco/trash/dto/RelevantTrashesDto.java
  src/main/java/com/sesacthon/foreco/trash/service/TrashService.java
  src/main/java/com/sesacthon/global/exception/ErrorCode.java
  src/main/java/com/sesacthon/infra/s3/exception/AiServerConnectionException.java
Labels: ✨ Feature

#106 docs: readme작성
  README.md
Labels: 📋 Docs
