Repository foreco-ibaji/Wiz-Server, pull requests merged in 2023-11, with the labels that each got.

#129 fix: ai모델을 사용한 이미지 검색api 엔드포인트 수정
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
Labels: ⭐ Refactoring, 🛠 Fix

#131 feat: 미션 아이콘 추가
  src/main/java/com/sesacthon/foreco/category/entity/Trash.java
  src/main/java/com/sesacthon/foreco/common/Icon.java
  src/main/java/com/sesacthon/foreco/mission/entity/Mission.java
Labels: ✨ Feature

#133 fix: ai모델을 사용한 이미지 검색 로직 및 응답 형태 수정
  src/main/java/com/sesacthon/foreco/mission/service/MissionService.java
  src/main/java/com/sesacthon/foreco/trash/service/TrashService.java
  src/main/java/com/sesacthon/infra/feign/client/mission/QuizMissionClient.java
  src/main/java/com/sesacthon/infra/feign/dto/request/ImageAnalyzeRequestDto.java
  src/main/java/com/sesacthon/infra/feign/dto/response/ImageAnalyzeResponseDto.java
  src/main/java/com/sesacthon/infra/s3/controller/S3Controller.java
  src/main/java/com/sesacthon/infra/s3/dto/AiImageAnalyzeDto.java
  src/main/java/com/sesacthon/infra/s3/dto/AnalyzedImageDetailDto.java
  src/main/java/com/sesacthon/infra/s3/dto/AnalyzedImageDto.java
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
Labels: ⭐ Refactoring, 🛠 Fix

#135 feat: 기업 미션 링크 url 추가
  src/main/java/com/sesacthon/foreco/mission/entity/Mission.java
  src/main/java/com/sesacthon/foreco/mock/mission/dto/MissionDetailDto.java
Labels: ✨ Feature

#137 refactor: ai모델을 활용한 이미지 검색 api응답 형태 수정
  src/main/java/com/sesacthon/infra/s3/dto/AiImageAnalyzeDto.java
  src/main/java/com/sesacthon/infra/s3/dto/AnalyzedImageDetailDto.java
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
Labels: ⭐ Refactoring

#139 fix: AI 분석 결과 중복 제거
  src/main/java/com/sesacthon/infra/s3/dto/AiImageAnalyzeDto.java
  src/main/java/com/sesacthon/infra/s3/dto/AnalyzedImageDetailDto.java
  src/main/java/com/sesacthon/infra/s3/service/S3Uploader.java
Labels: 🐞Bug, 🛠 Fix

#141 fix: ai퀴즈미션조회시 발생하던 500에러 해결
  src/main/java/com/sesacthon/foreco/category/repository/TrashRepository.java
  src/main/java/com/sesacthon/foreco/mission/service/MissionService.java
Labels: 🛠 Fix
